$modelname "props_jastiansummer/flashlight.mdl"
$model "Body" "flashlightpickup.smd"
$cdmaterials "swarm/models/weapons"
$hboxset "default"
$hbox 0 "mesh" -2.787  -8.308  -3.216  2.787  9.688  3.100
// Model uses material "FlashlightSkin.vmt"
$surfaceprop "weapon"
$illumposition -0.943 0.000 -0.058
$sequence idle "idle" fps 1.00
$collisionmodel "phymodel.smd"

$attachment muzzle mesh 0 -10 0 rotate 0 0 0